---
clients:
  - name: ollama
    type: ollama
    config:
      model: qwen3

flows:
  # Main workflow to extract news from ZDNet using Playwright MCP
  - name: zdnetNewsExtraction
    steps:
      - name: navigateToZDNet
        executor:
          type: mcp
          withConfig:
            server:
              name: "playwright"
              type: stdio
              command: "npx"
              args: ["@playwright/mcp"]
              env:
                PLAYWRIGHT_HEADLESS: "true"
                PLAYWRIGHT_BROWSER: "chromium"
              enabled: true
              timeout: 30s
            action: call_tool
            toolName: browser_navigate
            toolArgs:
              url: "{{.Variables.targetUrl}}"
            outputToContext: true

      - name: takePageSnapshot
        executor:
          type: mcp
          withConfig:
            server:
              name: "playwright"
              type: stdio
              command: "npx"
              args: ["@playwright/mcp"]
              env:
                PLAYWRIGHT_HEADLESS: "true"
                PLAYWRIGHT_BROWSER: "chromium"
              enabled: true
              timeout: 30s
            action: call_tool
            toolName: browser_snapshot
            outputToContext: true

      - name: extractNewsHeadlines
        executor:
          type: mcp
          withConfig:
            preset: playwright
            action: call_tool
            toolName: browser_click
            toolArgs:
              element: "tech news section"
              ref: "//section[contains(@class, 'news')]"
            outputToContext: true

      - name: getNewsLinks
        executor:
          type: llm
          withConfig:
            template: >-
              You are a web scraping assistant. Based on the following page snapshot, extract the latest tech news articles from ZDNet.

              Page content: {{.Text}}

              Find all news articles on this page and extract the following information for each:
              - Title
              - Summary (if available)
              - Link URL
              - Publication date (if available)

              Focus on the most recent tech news articles (today's date is {{.Variables.date}}).

              Return the result as a JSON object in this format:
              {
                "articles": [
                  {
                    "title": "Article title",
                    "summary": "Brief summary or excerpt",
                    "link": "https://www.zdnet.com/article/...",
                    "date": "2024-01-01"
                  }
                ],
                "source": "ZDNet",
                "date": "{{.Variables.date}}"
              }

              Only return the JSON object, no other text.
            outputJSON: true
            outputToContext: true

  # Workflow to summarize the extracted news using AI
  - name: newsSummarization
    steps:
      - name: generateSummary
        executor:
          type: llm
          withConfig:
            template: >-
              You are a tech news analyst. Please create a comprehensive summary of the following tech news articles from {{.Variables.source}}.

              News data: {{.Text}}

              Create a summary that includes:
              1. Overall tech trends mentioned in today's news
              2. Key companies or technologies featured
              3. Most significant developments
              4. Brief analysis of what these trends mean for the tech industry

              Keep the summary informative but concise (2-3 paragraphs).
              Write in a professional journalistic style.

              Do not include JSON formatting in your response - just provide the summary text.
            outputToContext: true
